name: sync
on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: clone
              run: |
                  git clone https://${{ secrets.TOKEN }}@github.com/fanhualuori/cdn-image.git --depth=1
                  git clone https://github.com/cdnjs/cdnjs.git --depth=1 --filter=blob:none --sparse
            - name: sync
              env:
                  packages: ${{ secrets.PACKAGES }}
              run: |
                  cd cdnjs
                  rm -rf ../static/libs/*
                  for i in $packages
                  do
                  echo Syncing $i
                  git sparse-checkout add ajax/libs/$i
                  cp -r ajax/libs/$i ../static/libs/$i
                  done
            - name: commit
              run: |
                  cd static
                  git config user.name fanhualuori
                  git config user.email 1370557600@qq.com
                  git add .
                  git commit --allow-empty -m "sync"
            - name: push
              run: |
                  cd static
                  git push https://${{ secrets.TOKEN }}@github.com/fanhualuori/cdn-image.git
